# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewWindow(object):
    def setupUi(self, NewWindow):
        NewWindow.setObjectName("MainWindow")
        NewWindow.resize(1075, 838)
        self.centralwidget = QtWidgets.QWidget(NewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.obj_pushButton = QtWidgets.QPushButton(self.centralwidget)  #搜索按钮
        self.obj_pushButton.setGeometry(QtCore.QRect(470, 340, 111, 31))
        self.obj_pushButton.setStyleSheet("QPushButton {  //按钮渐变背景\n"
"    font-size:12px;\n"
"    border-radius:2px;\n"
"    color:rgba(51,51,51,1);\n"
"    background:qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(242,242,242,1), stop:1 rgba(255,255,255,1));\n"
"    border:1px solid rgba(221,221,221,1);\n"
"}")
        self.obj_pushButton.setObjectName("pushButton")
        self.obj_lineEdit = QtWidgets.QLineEdit(self.centralwidget)  #目的基因输入
        self.obj_lineEdit.setGeometry(QtCore.QRect(460, 60, 151, 41))
        self.obj_lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)     #GENE  标题
        self.label_2.setGeometry(QtCore.QRect(510, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)    #Primer Size  文本
        self.label_3.setGeometry(QtCore.QRect(180, 150, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)    #Primer Tm    文本
        self.label_4.setGeometry(QtCore.QRect(180, 210, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)    #Primer GC%   文本
        self.label_5.setGeometry(QtCore.QRect(180, 270, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)    #Min          文本
        self.label_6.setGeometry(QtCore.QRect(310, 150, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)    #Opt          文本
        self.label_7.setGeometry(QtCore.QRect(490, 150, 31, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)    #Max          文本
        self.label_8.setGeometry(QtCore.QRect(670, 150, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)    #Max          文本
        self.label_9.setGeometry(QtCore.QRect(670, 210, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)   #Opt          文本
        self.label_10.setGeometry(QtCore.QRect(490, 210, 31, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)   #Min          文本
        self.label_11.setGeometry(QtCore.QRect(310, 210, 31, 16))
        self.label_11.setObjectName("label_11")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)    #Primer size  Min  数值
        self.spinBox.setGeometry(QtCore.QRect(360, 141, 81, 31))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)  #Primer size  Opt  数值
        self.spinBox_2.setGeometry(QtCore.QRect(550, 140, 81, 31))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)  #Primer size  Max  数值
        self.spinBox_3.setGeometry(QtCore.QRect(740, 140, 81, 31))
        self.spinBox_3.setObjectName("spinBox_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)  #Primer Tm  Min  数值
        self.doubleSpinBox.setGeometry(QtCore.QRect(360, 200, 81, 31))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)#Primer Tm  Opt  数值
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.centralwidget)#Primer Tm  Max  数值
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(740, 200, 81, 31))
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.centralwidget)#Primer GC  Max  数值
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(740, 260, 81, 31))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)     #Max          文本
        self.label_12.setGeometry(QtCore.QRect(670, 270, 41, 16))
        self.label_12.setObjectName("label_12")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.centralwidget)#Primer GC  Opt  数值
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(550, 260, 81, 31))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)     #Min          文本
        self.label_13.setGeometry(QtCore.QRect(310, 270, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)     #Opt          文本
        self.label_14.setGeometry(QtCore.QRect(490, 270, 31, 20))
        self.label_14.setObjectName("label_14")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.centralwidget)#Primer GC  Min  数值
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(360, 260, 81, 31))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)     #目的基因序列
        self.textBrowser.setGeometry(QtCore.QRect(180, 390, 691, 371))
        self.textBrowser.setObjectName("textBrowser")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(680, 50, 91, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(680, 90, 91, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        NewWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NewWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        NewWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NewWindow)
        self.statusbar.setObjectName("statusbar")
        NewWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(NewWindow)
        self.actionopen.setObjectName("actionopen")
        self.menufile.addAction(self.actionopen)
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(NewWindow)
        QtCore.QMetaObject.connectSlotsByName(NewWindow)

    def retranslateUi(self, NewWindow):
        _translate = QtCore.QCoreApplication.translate
        NewWindow.setWindowTitle(_translate("NewWindow", "Automatic gene probe"))
        self.obj_pushButton.setText(_translate("NewWindow", "Pick"))
        self.label_2.setText(_translate("NewWindow", "Gene"))
        self.label_3.setText(_translate("NewWindow", "Primer Size"))
        self.label_4.setText(_translate("NewWindow", "Primer Tm"))
        self.label_5.setText(_translate("NewWindow", "Primer GC%"))
        self.label_6.setText(_translate("NewWindow", "Min"))
        self.label_7.setText(_translate("NewWindow", "Opt"))
        self.label_8.setText(_translate("NewWindow", "Max"))
        self.label_9.setText(_translate("NewWindow", "Max"))
        self.label_10.setText(_translate("NewWindow", "Opt"))
        self.label_11.setText(_translate("NewWindow", "Min"))
        self.label_12.setText(_translate("NewWindow", "Max"))
        self.label_13.setText(_translate("NewWindow", "Min"))
        self.label_14.setText(_translate("NewWindow", "Opt"))
        self.checkBox.setText(_translate("NewWindow", "HUMAN"))
        self.checkBox_2.setText(_translate("NewWindow", "MUS"))
        self.menufile.setTitle(_translate("NewWindow", "file"))
        self.actionopen.setText(_translate("NewWindow", "open"))
        self.obj_lineEdit.setPlaceholderText(_translate("NewWindow", "目的基因序列号"))
